name: englishword
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/A1.txt
    - assets/A2.txt
    - assets/B1.txt
    - assets/B2.txt
    - assets/C1.txt
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#667eea"
  adaptive_icon_foreground: "assets/logo.png"